db.lifts.insert([
	{
		workoutName: 'Upper Body 1',
		description: 'Shoulders and Arms workout',
		focus: 'Shoulders',
		numExercises: 5,
		totalWeightLifted: 200,
		completed: true,
	},
	{
		workoutName: 'Upper Body 2',
		description: 'Shoulders and Arms workout',
		focus: 'Arms',
		numExercises: 5,
		totalWeightLifted: 125,
		completed: true,
	},
	{
		workoutName: 'Lower Body 1',
		description: 'Legs and Back',
		focus: 'Legs',
		numExercises: 7,
		totalWeightLifted: 750,
		completed: false,
	},
	{
		workoutName: 'Upper Body 1',
		description: 'Shoulders and Arms workout',
		focus: 'Shoulders',
		numExercises: 5,
		totalWeightLifted: 250,
		completed: true,
	},
	{
		workoutName: 'Upper Body 2',
		description: 'Shoulders and Arms workout',
		focus: 'Arms',
		numExercises: 5,
		totalWeightLifted: 150,
		completed: false,
	},
	{
		workoutName: 'Lower Body 1',
		description: 'Legs and Back',
		focus: 'Legs',
		numExercises: 7,
		totalWeightLifted: 900,
		completed: true,
	},
]);
